import bluetooth
import threading

from adxl345 import ADXL345
import adxl345
import os       
import picamera         # the camera video output library
from PIL import Image   # to create image using preset png
from time import sleep
import json             # for JSON object parsing

def bash_command(bash_cmd):
    import subprocess
    subprocess.Popen(bash_cmd, stdout=subprocess.PIPE, shell=True)
#bluetooth name for raspberry pi is "raspberrypi"

# function to update the LCD display
def display_update(turn, distance_left, upcoming_road, end, new_maneuver)
    
    
    camera.annotate_text= turn + " on " +    
    

# function to decode JSON file and calles the display function
def display(json_str):
    json_object     = json.loads(json_str)
    turn            = json_object["turn"]
    distance_left   = json_object["distance"]
    upcoming_road   = json_object["road"]
    # boolean flag to indicate if we reached our destination
    end             = json_object["end"]
    # boolean indictaing if we changed road or just continuing on the same road
    new_maneuver    = json_object["newManeuver"]
    display_update(turn, distance_left, upcoming_road, end,new_maneuver)    


def check_g_force():
    
    while True:        
        axes = acc.getAxes(True)
        # print "ADXL345 on address 0x%x:" % (acc.address)
        if axes['x'] > MAX_G or axes['y'] > MAX_G or axes['z'] > MAX_G:
            message = "Crash"
            inputSocket.send(message.encode())
            sleep(20)

def readIncomingData(inputSocket):
    while True:
        data=inputSocket.recv(1024)
        print "received [%s] \n " % data
        
        # data will be a json string
        display(data)
        
        
def runServer():
    
    global serverSocket, inputSocket
    # you had indentation problems on this line:
    serverSocket=bluetooth.BluetoothSocket(bluetooth.RFCOMM)
    port = 1

    serverSocket.bind(("",port))
  
    print "Listening for connections on port: ", port   

    # wait for a message to be sent to this socket only once
    serverSocket.listen(1)
    port=serverSocket.getsockname()[1]
   
    # you were 90% there, just needed to use the pyBluez command:
    bluetooth.advertise_service( serverSocket, "SampleServer",
                        service_id = uuid,
                        service_classes = [ uuid, bluetooth.SERIAL_PORT_CLASS ],
                        profiles = [bluetooth.SERIAL_PORT_PROFILE] 
                        )

    inputSocket,address = serverSocket.accept()
    print "Accepted connection"
    print "Got connection with" , address
    
    

try:
    # set up camera and start it 
    camera = picamera.PiCamera()    
    camera.resolution = (1280, 720) # set up resolution
    camera.framerate = 24
    camera.brightness = 75
    camera.contrast = 75
    
    # set the text color
    camera.annotate_background = Color('red')
    # text size
    camera.annotate_text_size = 100      
    
        
    # the max G before the RPI trigger the SMS
    MAX_G = 5

    #intialize the accerelometer
    acc = ADXL345()
    acc.setRange(adxl345.RANGE_16G)
    acc.setBandwidthRate(adxl345.BW_RATE_50HZ)
    
    name="bt_server"
    target_name="test"
    # some random uuid, generated by https://www.famkruithof.net/uuid/uuidgen
    uuid="0fee0450-e95f-11e5-a837-0800200c9a66"
    serverSocket = None
    inputSocket = None
    
    # start the bluetooth connection with android app
    runServer()
    # start a receiving thread
    receiveThread = threading.Thread(target=readIncomingData, args=(inputSocket,))
    receiveThread.daemon = True
    receiveThread.start()
    
    
    # start a sending thread for crash detection    
    crashThread  = threading.Thread(target=check_g_force, args=(acc,))
    crashThread.daemon = True
    crashThread.start()
    
except KeyboardInterrupt:
    serverSocket.close()
    inputSocket.close()
